import {generateWorld as generatePreviousWorld} from './adventure-world-v5.js';
import {generateWorld as generateLegacyWorld} from './adventure-world-v3.js';
import { generateWorld, approachPath, nextSeed, rng, ENEMIES } from './adventure-world.js';
import { findPath } from './demo-world.js';
export const COUNTERS=['xpTotal','gold','earned','spent','potions','potionsFound','wins','defeats','discoveries','circuits','completed','upgrades','lootSold'];
export const BALANCE={enemyDamage:.068, hazardChance:.045, hazardMultiplier:2.1};
export function sqrt(n){if(n<2n)return n;let x=1n<<BigInt(Math.ceil(n.toString(2).length/2));while(true){const y=(x+n/x)/2n;if(y>=x)return x;x=y;}}
export function levelFor(xp){return (sqrt(484n+8n*xp)-22n)/4n+1n;}
export const levelBase=l=>2n*(l-1n)*(l-1n)+22n*(l-1n);
export const xpNeeded=l=>24n+4n*(l-1n);
export const maxHealth=l=>30n+5n*l+5n*(l/10n);
export function money(n){return format(n/10n)+(n%10n?'.'+n%10n:'');}
export function format(n){if(typeof n==='number')return String(Math.round(n));const s=String(n);return s.length<10?BigInt(s).toLocaleString('en-GB'):s.slice(0,4)+'… ('+s.length+' digits)';}
export function tale(s,title,text,quality){s.event={title,text,...(quality?{quality}:{})};s.log.unshift(s.event);s.log.length=Math.min(s.log.length,10);}
export function freshGame(seed=Date.now()>>>0){const s={version:2,seed,previousRegion:'',recentNames:[],mapNumber:1n,bossIn:2+((seed>>>16)%2),mapBoss:false,level:1n,hp:1,gear:{weapon:null,armour:null,charm:null},name:'Rowan',hero:'knight',log:[],event:{title:'A journey begins',text:'Rowan takes the road, with room in the day for a little wonder.'},lastEnemy:'',card:null};for(const k of COUNTERS)s[k]=0n;s.potions=3n;startMap(s);return s;}
export function worldFor(s){const w=(s.generation===3?generateLegacyWorld:[4,5].includes(s.generation)?generatePreviousWorld:generateWorld)(s.seed,s.mapNumber,s.previousRegion,s.recentNames,s.mapBoss,s.generation??7);for(const o of w.objects)if(o.type==='combat'&&s.enemyOverrides?.[o.id])o.kind=s.enemyOverrides[o.id];return w;}
export function startMap(s){s.generation=7;s.enemyOverrides={};const w=worldFor(s);s.x=w.entrance.x;s.y=w.entrance.y;s.fraction=0;s.route=[];s.stop=0;s.stage='plan';s.timer=0;s.duration=0;s.visited=new Set();s.completedQuests=new Set();s.checkpoint={...w.entrance};s.mapGold=0n;s.mapElapsed=0;s.target=null;s.enemy=null;s.recovery=0;s.mapDefeats=0;return w;}
export function gainXP(s,n){s.xpTotal+=n;const old=s.level;s.level=levelFor(s.xpTotal);if(s.level>old){s.hp=Math.min(1,s.hp+.12);if(s.level/10n>old/10n)tale(s,'A little taller in spirit','Ten more levels of road wisdom make Rowan stronger and hardier.');}}
function earn(s,n){s.gold+=n*10n;s.earned+=n*10n;s.mapGold+=n*10n;}
export function buy(s){const cost=80n;if(s.potions<3n&&cost<=s.gold/4n){s.gold-=cost;s.spent+=cost;s.potions++;}const travel=350n;if(s.circuits%4n===3n&&s.lastUpgradeMap!==s.mapNumber&&travel<=s.gold/4n){s.gold-=travel;s.spent+=travel;s.upgrades++;s.lastUpgradeMap=s.mapNumber;}}
const quality=['Common','Fine','Rare','Mythic'], adjective=['Wayfarer’s','Kindly','Rainkeeper’s','Dawnwoven'], nouns={weapon:['Blade','Staff','Bow'],armour:['Coat','Mantle','Vest'],charm:['Bell','Button','Compass']};
export function loot(s,seed,forcedSlot){const r=rng(seed),slot=forcedSlot||['weapon','armour','charm'][Math.floor(r()*3)],roll=r(),tier=roll<.6?0:roll<.88?1:roll<.985?2:3;const item={slot,level:s.level,quality:quality[tier],tier,name:adjective[tier]+' '+nouns[slot][Math.floor(r()*3)]};const old=s.gear[slot];if(!old||item.level*10n+BigInt(tier)>old.level*10n+BigInt(old.tier)){s.gear[slot]=item;if(old){earn(s,3n+BigInt(old.tier)*2n);s.lootSold++;}tale(s,'A useful find',`Rowan equips the ${item.quality.toLowerCase()} ${item.name}. ${old?'The previous piece finds a new owner.':'It feels like a good companion for the road.'}`,item.quality);}else{earn(s,3n+BigInt(tier)*2n);s.lootSold++;}}
const mod=(s,slot)=>s.gear[slot]?(.025+s.gear[slot].tier*.012):0;
export function heal(s){if(s.hp<=.2&&s.potions>0n){s.potions--;s.hp=Math.min(1,s.hp+.3);return true;}return false;}
export function defeat(s){const loss=s.mapGold/10n;s.gold-=loss>s.gold?s.gold:loss;s.defeats++;s.mapDefeats++;s.hp=0;s.stage='recovery';s.recovery=10;s.timer=10;s.duration=10;s.x=s.checkpoint.x;s.y=s.checkpoint.y;s.fraction=0;s.route=[];tale(s,'A small setback','Rowan wakes at the last safe stop. The road keeps its place, and ten quiet seconds bring courage back.');}
function plan(s,w){s.target={...w.stops[s.stop]};if(s.target.type==='combat'&&s.target.kind===s.lastEnemy){s.target.kind=ENEMIES[(ENEMIES.indexOf(s.lastEnemy)+1)%ENEMIES.length];s.enemyOverrides??={};s.enemyOverrides[s.target.id]=s.target.kind;w.stops[s.stop].kind=s.target.kind;}s.route=approachPath(w,s,s.target);s.walkStep=.48;s.fraction=0;s.stage='walk';s.event={title:'Along the road',text:`Rowan follows the winding path through ${w.name}.`};}
function arrive(s){const o=s.target;s.stage=o.type==='combat'?'combat':'visit';s.timer=s.duration=s.stage==='combat'?.55:3;if(s.stage==='combat'){const r=rng(o.roll);const offset=o.boss?2+Math.floor(r()*3):[-2,-1,0,0,0,1,2][Math.floor(r()*7)];const level=s.level+BigInt(offset)>0n?s.level+BigInt(offset):1n;const hazard=r()<BALANCE.hazardChance;s.enemy={hp:1,level,offset:Number(level-s.level),round:0,seed:nextSeed(o.roll),hazard,retries:0};s.duration=combatRemaining(s);s.lastEnemy=o.kind;s.event={title:o.boss?'A guardian of the road':'A meeting on the trail',text:`A ${o.kind.replaceAll('-',' ')} steps forward. Rowan takes a steady breath.`};}else s.event={title:o.title||({rest:'A sheltered fire',traveller:'A companion for a moment',shrine:'A candle in the quiet',treasure:'Something tucked away',discovery:'A small wonder',exit:'The next horizon'}[o.type]),text:o.text||'The road offers a little kindness. Rowan takes a moment to notice it.'};tale(s,s.event.title,s.event.text);}
function finish(s,w){const o=s.target;s.visited.add(o.id);if(o.type==='combat'){s.wins++;const reward=o.boss?2n:1n;earn(s,18n*reward);gainXP(s,12n*reward+BigInt(Math.round(Number(12n*reward)*mod(s,'charm'))));if(o.boss)s.card={title:'The guardian gives way',text:'Courage has made a little more room on the road.',seconds:10};if(o.roll%3===0)loot(s,o.roll);if(o.roll%4===0){s.potions++;s.potionsFound++;}}else if(o.type==='quest'){s.completed++;s.completedQuests.add(o.quest);earn(s,15n);gainXP(s,10n);s.checkpoint={x:s.x,y:s.y};}else if(o.type==='rest'||o.type==='shrine'){s.hp=Math.min(1,s.hp+.35+Number(s.upgrades*100n/(s.upgrades+20n))/2000);s.checkpoint={x:s.x,y:s.y};}else if(o.type!=='quest-start'&&o.type!=='exit'){s.discoveries++;gainXP(s,4n);earn(s,8n);if(o.type==='treasure'){s.potions++;s.potionsFound++;}}
 buy(s);s.stop++;s.stage='plan';s.enemy=null;s.target=null;
 if(s.stop===w.stops.length){if(s.completedQuests.size!==w.quests.length)throw Error('Unfinished map quest');s.lastMapDuration=s.mapElapsed;s.circuits++;s.card={title:`${w.name} complete`,text:'Every promise kept. Another path opens ahead.',seconds:5};s.previousRegion=w.region;s.recentNames=[w.name,...s.recentNames].slice(0,10);s.mapNumber++;s.seed=nextSeed(s.seed);s.bossIn--;s.mapBoss=s.bossIn===0;if(s.mapBoss)s.bossIn=2+((s.seed>>>16)%2);startMap(s);return true;}return false;
}
function strike(s,w){const e=s.enemy,r=rng(e.seed);e.seed=nextSeed(e.seed);e.round++;e.hp-=.112*(1+mod(s,'weapon'))*(.9+r()*.2)/(s.target.boss?1.18:1);if(e.hp<=0)return finish(s,w);const damage=BALANCE.enemyDamage*(1+e.offset*.055)*(s.target.boss?1.16:1)*(e.hazard?BALANCE.hazardMultiplier:1)*(1-mod(s,'armour'))*(.7+r()*.6)*(e.retries?.22:1);s.hp-=damage;heal(s);if(s.hp<=0)defeat(s);else s.timer=.55;return false;}
// Normal simulation; realDt is separate so recovery and cards are never sped up.
export function advanceGame(s,w,dt,realDt=dt){let left=Math.max(0,dt),realLeft=Math.max(0,realDt);if(s.card){s.card.seconds-=realDt;if(s.card.seconds<=0)s.card=null;}if(s.stage==='recovery'){const used=Math.min(realLeft,s.recovery);s.recovery-=used;s.timer=s.recovery;s.mapElapsed+=used;if(s.recovery>1e-8)return false;s.hp=1;s.stage='return';s.route=approachPath(w,s,s.target);s.fraction=0;left=Math.max(0,left-used*(dt/realDt||1));}
 let transitions=0;while(left>1e-8&&transitions++<10000){if(s.stage==='plan')plan(s,w);if(s.stage==='walk'||s.stage==='return'){if(!s.route.length){if(s.stage==='return'){s.stage='combat';s.enemy.retries++;s.timer=.55;}else arrive(s);continue;}const step=.48;const elapsed=Math.min(left,(1-s.fraction)*step);s.fraction+=elapsed/step;left-=elapsed;s.mapElapsed+=elapsed;if(s.fraction>=1-1e-8){const p=s.route.shift();s.x=p.x;s.y=p.y;s.fraction=0;}}else{const elapsed=Math.min(left,s.timer);s.timer-=elapsed;left-=elapsed;s.mapElapsed+=elapsed;if(s.timer<=1e-8){if(s.stage==='combat'){if(strike(s,w))return true;if(s.stage==='recovery')return false;}else if(finish(s,w))return true;}}}return false;}

// Predict remaining exchanges using a private RNG; never advance actual combat state.
export function combatRemaining(s){
 let hp=s.enemy.hp,seed=s.enemy.seed,rounds=0;
 while(hp>0&&rounds<30){const r=rng(seed);seed=nextSeed(seed);hp-=.112*(1+mod(s,'weapon'))*(.9+r()*.2)/(s.target.boss?1.18:1);rounds++;}
 return Math.max(0,s.timer)+(rounds-1)*.55;
}
export function encounterProgress(s){return Math.max(0,Math.min(1,(s.stage==='combat'?combatRemaining(s):s.timer)/s.duration));}
